name: build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    name: Build and Release m3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build with Makefile
        run: make

      - name: Check if binary exists
        run: test -f ./m3

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./m3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

